version: 2.1
defaults: &defaults
  machine:
    image: ubuntu-1604:201903-01
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  restore_cache:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: sample.txt-{{ checksum "sample.txt" }}
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: "./match-deps.sh"
      - run: "dd if=/dev/urandom of=sample.txt bs=5G count=1"
      - save_cache:
          key: sample.txt-{{ checksum "sample.txt" }}
          paths:
            - .

workflows:
  version: 2
  append_and_cache:
    jobs:
      - checkout
      - restore_cache:
          requires:
            - checkout
      - test:
          requires:
            - checkout
            - restore_cache
