version: 2.1
defaults: &defaults
  machine:
    image: ubuntu-1604:201903-01
orbs:
  rust: glotrade/rust@0.1.3
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  restore_cache:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: massive-target-dir/Cargo.lock-{{ checksum massive-target-dir/Cargo.lock }}
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: "./match-deps.sh"
  build_rust_project:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - rust/update_toolchain:
          toolchain: nightly
      - rust/build
      - save_cache:
          key: massive-target-dir/Cargo.lock-{{ checksum massive-target-dir/Cargo.lock }}
          paths:
            - massive-target-dir/target

workflows:
  version: 2
  append_and_cache:
    jobs:
      - checkout
      - restore_cache:
          requires:
            - checkout
      - test:
          requires:
            - checkout
            - restore_cache
      - build_rust_project:
          requires:
            - checkout
            - restore_cache
