version: 2.1
defaults: &defaults
  machine:
    image: ubuntu-1604:201903-01
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  restore_cache:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: test.txt-{{ checksum "dummy-deps/dummy.lock" }}
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: "./match-deps.sh"
  save_cache:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - save_cache:
          key: test.txt-{{ checksum "dummy-deps/dummy.lock" }}
          paths:
            - dummy-deps

workflows:
  version: 2
  append_and_cache:
    jobs:
      - checkout
      - restore_cache:
          requires:
            - checkout
      - test:
          requires:
            - checkout
            - restore_cache
      - save_cache:
          requires:
            - checkout
            - restore_cache
            - test
