version: 2.1
defaults: &defaults
  machine:
    image: circleci/classic:latest
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - run: "touch sample.txt"
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    <<: *defaults
    parallelism: 2
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: sample.txt-{{ checksum "sample.txt" }}
      - run: "./match-deps.sh"
      - run:
          command: "dd if=/dev/urandom of=sample.txt bs=250M count=15 iflag=fullblock"
          no_output_timeout: 30m
      - save_cache:
          key: sample.txt-{{ checksum "sample.txt" }}
          paths:
            - .

workflows:
  version: 2
  append_and_cache:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
