version: 2.1
jobs:
  append-and-cache:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - restore_cache:
          key: test.txt-{{ checksum "dummy-deps/dummy.lock" }}
      - run:
          name: dummy test
          command: "true"
      - save_cache:
          key: test.txt-{{ checksum "dummy-deps/dummy.lock" }}
          paths:
            - dummy-deps

workflows:
  append_and_cache:
    jobs:
      - append-and-cache
